### ISSUE TITLE
Source Auto Power

### ISSUE THREAD

**Issue by ironcross13** [adelyte/crescendo#10]
Appears to be broken since change to ID scheme (i.e D5 --> 50).  Does not work in Rooms-Source program nor in local program using modules from Rooms-Sources branch.

Watching debugger the Connected! signal never appears to go high so the Power_On never fires in Source Module.

While trying to track down issue noticed that in Room module (S-4.1.6.3) the AtoS still references D5.  The same is true for the Interface module (S-3.5.2), AtoS and (S-2.3.5.2) Analog Equate reference D5.  Should these now be 50 as well?

**Comment by ironcross13** [comment]
With regards to the Power issue:  The [Connected] signal from the cross-point is staying high at all times.  One of the cross-point connections is never releasing.

**Comment by adelyte-chris** [comment]
Nice catch, Josh.

The rooms-sources branch is a feature branch for Crescendo 2.0. It will be transitional until it is merged into develop.

I will fix the "\xD5" references you found in my next push.

The `Sources` module works by maintaining a persistent crosspoint connection to every source. We need other global data modules like `Lights`, `Shades`, and `Climates`, so `ECROSS:Connected` will become a useless slot on most models.

The power problem also affects music sources that connect to main sources (`TiVo Music`, `DirecTV Music`, etc).

We will expand the same workaround we use for `Source:In_Use` (_see_ `Source:S-1.2:dig-i1`). We will also remove or replace all crosspoint status slots (`Connected`, `Connected!`, etc).

**Comment by adelyte-austin** [comment]
I will a final review of all auto-power, connected? and connected! outputs in feature/demo before merging to the Master branch.
