### ISSUE TITLE
[Crescendo 2.0] Default rooms and room sources

### ISSUE THREAD

**Issue by adelyte-chris** [adelyte/crescendo#11]
Add parameters to the `Rooms` and `Sources` global data models for default rooms and room sources. 

If the `Rooms-Sources Controller:Rooms` parameter is left blank, use the value from `Rooms:Default Rooms`. If the `Room:Sources` parameter is left blank, use the value from `Sources:Default Sources`.

**Comment by adelyte-austin** [comment]
This issue is closed.
