### ISSUE TITLE
Room Icon Request

### ISSUE THREAD

**Issue by ironcross13** [adelyte/crescendo#17]
Could a parameter and logic for an icon for the room module be added?

**Comment by adelyte-chris** [comment]
As in icons representing the actual room, for example [kitchen icons](https://thenounproject.com/search/?q=kitchen)?

**Comment by ironcross13** [comment]
Correct.  Just like with sources.  That way an image can be used to represent the room in lists etc.

**Comment by adelyte-chris** [comment]
That's no problem.

**Comment by adelyte-austin** [comment]
UIs currently use a custom Crescendo icon for the room select. This is inadequate for actual systems since it has little meaning to end users.
