### ISSUE TITLE
Switcher Pulse Stretching

### ISSUE THREAD

**Issue by adelyte-austin** [adelyte/crescendo#18]
Many IR controlled switchers do not respond to the minimal IR signal cerated by a logic wave pulsing the IR driver. There needs to be a way to use a programmer-defined "pulse time" output of switcher to handle these devices, while avoiding hitting the clock of the processor for every switcher power event.

**Comment by adelyte-chris** [comment]
It's not possible to have a minimum time without hitting the processor clock.

We could:
1. Use two modules (one for switchers with IR control, one for the rest),
2. Attach timers to all switcher power and input events, or
3. Use a MOS between switcher modules and IR drivers as needed.

Perhaps there is another option I am forgetting. My preference is the third option.

**Comment by adelyte-austin** [comment]
IR can be unpredictable, affected by the environment (placement / ambient light), driver integrity, and results even vary between Crestron ports (Processor vs Room Boxes). I've seen mixed results from the Sony XBR9000 driver found in the cdb. A Power_On logic-wave-pulse worked in one system, but required stretching in another. This causes confusion and time wasted, especially for less experienced techs.

The MOS method was included in the 1.0 release, and has been used successfully in many projects. All things considered, option 3 makes sense to me. Crescendo docs should include a Quick reference manual, that explains this work around, and other best practices for configuring and testing systems.
