### ISSUE TITLE
Source Power

### ISSUE THREAD

**Issue by ironcross13** [adelyte/crescendo#19]
Source Power Off command is not fired on Room Off.  During Room On sequence both Source Power On & Power Off are going high.  Issue Present in latest Develop & Feature-Demo branches.

**Comment by ironcross13** [comment]
Auto Power Parameter on Source module now based off of Ah & Bh values but Auto Power Enabled EQU (4.1.1) in Source module is looking for 1d.

Blu-Ray module still has 1d as parameter value for Auto Power.  

Source power still not firing when room off is fired.  Even with the above issue addressed and no other rooms using the source.

**Comment by adelyte-chris** [comment]
You're too fast for me. I'm making a second, thorough audit pass over sources today.

**Comment by adelyte-austin** [comment]
In the wild auto-power is mostly used on Blu-ray players. Often I will link `Power On` to a discrete, or the play command and leave the `Power Off` output blank to prevent a shutdown when the user switches sources (for instance, to check a camera dvr) then switch back to Blu-ray.
Especially in the case of local sources, buffering the Room's TV power on and off to the source power works well. How can we integrate a solution for this dilemma into the framework?

**Comment by adelyte-chris** [comment]
I've already put a 2 minute delay on power off, which could be changed depending on the situation.
