### ISSUE TITLE
Feature/Demo Branch

### ISSUE THREAD

**Issue by ironcross13** [adelyte/crescendo#20]
Issues since 2016-02-04 commit
- iPad & iPhone Crestron App Project Name in program does not match VTPro Project Name.  In Program they are referenced as Crestron iPad and Crestron iPhone.  VTPro projects are name Crescendo iPad and Crescendo iPhone.  Results in failed load of GUI on device
- Room Menu not populating on tablets.  Default Room not loading on tablets.  Appears that the revised modules are not passing metadata correctly.  Manual setting of values via debugger does not result in any changes.

**Comment by adelyte-chris** [comment]
I'll work on runtime bugs after I have finished auditing the core modules, which I expect will be today or tomorrow. There's no sense in fixing bugs only to introduce them again.
