### ISSUE TITLE
[Crescendo 2.0] Remove extraneous modules

### ISSUE THREAD

**Issue by adelyte-chris** [adelyte/crescendo#22]
Modules in `program` directory not in the `Crescendo MC3` program:
- [x] Crescendo Cloud
- [x] Crestron BIPAD
- [x] Keypad
- [x] Touchscreen

**Comment by adelyte-austin** [comment]
Keypad should be considered for release. @adelyte-chris

**Comment by ironcross13** [comment]
I realize it is merely semantics but "Tablet" seems to be an inappropriate name for the module if it is going to be used tor actual touchpanels as well.  It seems like there should be a separate module for actual non tablet/phone devices.  The App URL jumps aren't supported by the touchpanels.

Also, if you want I can send you my switcher module that I modified to represent a C2N-AMP-6X100.  Same structure as the SWAMP module, which I realize could bee used.

**Comment by adelyte-austin** [comment]
@ironcross13 You are right about Tablet being a misnomer. This fixes and additions from `Tablet` will be merged back into the previous generic interface module called `Touchscreen`.

**Comment by adelyte-chris** [comment]
The modules are extraneous to the demo, not necessarily extraneous to other projects using the framework.

Removing the modules is not a design decision, it is a marketing decision, and it is not intended to last forever. We're releasing the minimal module set used by the demo—fully audited and normalized. We'll release other modules as we audit and normalize them. We'll create a repository for orphaned modules and ask the community to help maintain them.

As to `Tablet` vs alternatives, if we're using the same interface module for tablets and phones, I suggest `App`.

@ironcross13 We would very much appreciate a pull request for the `Crestron C2N-AMP-6X100` module after we have merged feature/demo to master.
