### ISSUE TITLE
Switcher Off issue

### ISSUE THREAD

**Issue by ironcross13** [adelyte/crescendo#27]
I’ve come across the following issue while testing out the release version.  Prior commits from the feature-demo branch did not exhibit this issue.  Not sure which commit precisely is where issue cropped up.

I have a source with ID 22.  When it is selected it is causing the AVR switcher module to fire the power off signal.  The source is not listed on the AVR switcher module as a “source for power off”.  If I change the Source ID to something different, say 24, and adjust all modules accordingly then the issue is no longer present.  

I have attached a debug log with module signals included and a screenshot of the pertinent module parameters.
[Input issue files.zip](https://github.com/adelyte/crescendo/files/157986/Input.issue.files.zip)

**Comment by adelyte-austin** [comment]
The bug must have snuck in as part of the changes made for cloud blueprint compatibility. This will be fixed by Monday if not sooner.

**Comment by adelyte-austin** [comment]
I get the same behavior on Source ID 22. The `Input_Found_First` output of `Index Of.usp` triggers for some, but not all of the room's switchers. This is not the case when the ID is changed from 22 to 23, as you've mentioned. Still looking into this issue.
