### ISSUE TITLE
iPad Room Names / Lighting not populating

### ISSUE THREAD

**Issue by patrickhampson** [adelyte/crescendo#34]
![img_0001](https://cloud.githubusercontent.com/assets/1509566/15638901/5176b3a6-25f3-11e6-96af-157d7b1735af.jpg)

Having an issue where text does not always display in the Rooms and Lighting menu.  Sources menu is usually ok.  This is running on a 2 series processor and another touch panel in the system (wired TSW-1052) seems to work fine.  When sending data to the T-01  Move_01_Room_Is$, the crestron app responds correctly but on this particular panel there is no data pre-populated like there is with the other panel.

What could the cause of this be?
Thanks!

**Comment by Tecrench** [comment]
Scrolled to end? Like using when 14 of 32 rooms?

**Comment by adelyte-chris** [comment]
List length parameters shouldn't permit the list to be scrolled beyond valid its valid items.

Would you attach or email me your program so that I can troubleshoot it?

**Comment by adelyte-austin** [comment]
Thanks for posting this issue @patrickhampson 
Most of our testing has been done on 3 series processors, but the framework is intended to be fully 2-series compatible. I once saw missing items in the sub-ref-lists in the Loft demo, on a PRO2. I attributed it to signals lost in the processor conversion. I'll look into this deeper given you're having similar issues. If you'd like me to test your program please email it to austin@adelyte.com.

**Comment by patrickhampson** [comment]
Thanks Austin, I sent it to Chris but i'll forward your way as well.  I will try and do some testing with a 3 series processor to see what the results are.

**Comment by adelyte-chris** [comment]
My fault, I should've forwarded it.

**Comment by adelyte-austin** [comment]
This is a problem unique to 2 series. It appears the strings connected to smart-graphics-extenders are not permanent, despite there being a make-string-permanent symbol inside the Rooms-Sources Controller module. Pulsing the signal _//Z__System_Reinitialize_ once your iPad is connected will populate all strings.
As a work around, add an additional msp in the T-XX folder for any mobile device, and attach all serial signals connected on the subpage reference lists. I will put this issue in front of Crestron.

**Comment by adelyte-austin** [comment]
Documentation will be posted on adelyte.com/crestron/crescendo/docs that details converting The Loft demo to run on 2-series processors.

There are only 2 issues known at this time:
-Strings connected to smart graphics extenders are Impermanent in 2-series programs.
-The `Media Server Object Router v3.0` from Crestron is not 2-series compatible.
