### ISSUE TITLE
Parameter Bug in Crestron SWAMP module

### ISSUE THREAD

**Issue by DR7** [adelyte/crescendo#37]
When choosing to enter a parameter for "Sources for input X" sometimes a drop down field will appear in blue and when clicked a second time a large blank list appears, when this happens a person cannot enter text.

A temp workaround is to click fields higher up the parameter list and enter your data then copy and paste in the problematic parameter fields and this will work, then go back to the other fields you put temp pasting data into and fill them with ""

**Comment by adelyte-austin** [comment]
Thank you for bringing this to our attention. This has been fixed in the master branch.
