### ISSUE TITLE
Room with ID 11, will not populate Share menu, on all TP

### ISSUE THREAD

**Issue by dballos** [adelyte/crescendo#38]
When change Room ID to other than 11 its work fine

**Comment by adelyte-austin** [comment]
Can you send a private link to your code to austin@adelyte.com so I can review the configuration?

**Comment by adelyte-austin** [comment]
Room 11, which should be in symbol position S-2.1.12, is actually not defined in your program. The default rooms parameter which reads, `\x01\x02\x03\x04\x05\x06\x07\x08\x09\x10\x12\x13\x14\x15\x16\x17` indicates 11 was removed intentionally. Did Room 11 exist once, but then merged with another zone? Skipping IDs is perfectly acceptable in the framework, so long as the ID is not referenced elsewhere.

**Comment by dballos** [comment]
i Know
I remove Room 11 because it didnt work for sharing

**Comment by dballos** [comment]
But what about Keypad issue (error on compile), could you give me hint

**Comment by adelyte-austin** [comment]
You have a good looking build here! It seems like most things are working well. As for the sharing issue, I lean toward it being a configuration error. I'm currently testing a 20 room system and Room 11 is present in all menus it's defined. I would need a full archive with room 11 still defined, so I can compile and test. Or, perhaps we can set up a short screen share sometime next week to look at it. 
Which module errors during the compile?

**Comment by dballos** [comment]
WARNING(LGCMCVT224)
        Module S-1 in S-4.3.4 (Module file C:\Program Files
(x86)\Crestron\Simpl\USRMACRO\Keypad.umc) is incomplete.
WARNING(LGCMCVT126)
        Signal "__K__Initialized!" in S-4.3.4 (Module name C:\Program Files
(x86)\Crestron\Simpl\USRMACRO\Keypad.umc) has no driving source.

**Comment by dballos** [comment]
Austin
Sorry , I fix it
I just realize i need resynch SELF module inside KEYPAD module
its compile w/o errors
Thanks a lot

**Comment by adelyte-austin** [comment]
Keypad.umc was taken out of the production release of The Loft demo, but was not removed from the program directory. It is a useful interface module, (Type C for ccross) so I will commit a synched version to the master branch for other users.

Did you solve the room 11 sharing issue as well? @dballos

**Comment by dballos** [comment]
Thanks Austin ,
I didn't have chance to test room 11
Yet
