### ISSUE TITLE
Touchscreen Join #'s on Device Modules

### ISSUE THREAD

**Issue by tjtoney** [adelyte/crescendo#4]
I think it may be useful to have the signal prompts on the source and other device modules to include the corresponding touchscreen join #. 

I think it would make it easier when building or modifying the VTPro file.

**Comment by adelyte-austin** [comment]
TJ - I agree, given the platform, and the high likelihood that users of the framework have little experience with crosspoint routing, it would make sense to start the Device/Source modules at _101 rather than _001, as 101 is the join number these signals map back to on interfaces.

**Comment by adelyte-austin** [comment]
This will be done in the upcoming 2.0 release

**Comment by adelyte-austin** [comment]
This issue is now back up for discussion with the addition of separate Source and Device crosspoint layers. Starting all generic crosspoint signals at 001, regardless of join offsets allows for moving and expansion later on, without concern for hard coded slot names being made incorrect.

**Comment by adelyte-chris** [comment]
Smart Graphics seem to make hard-assigned joins less relevant than they were previously. I like any idea that will make development easier on programmers, but I don't think we can maintain consistency. I'll reopen if someone presents a renewed argument.
