### ISSUE TITLE
TSR-302 Rooms button is grey

### ISSUE THREAD

**Issue by DR7** [adelyte/crescendo#42]
Hello, in the Loft example I notice the "Rooms" button is greyed out on a TSR-302 and I've tried to fix the problem but can't seem to even find what might be causing the problem.

I notice in the template the Enable Join has been set to 2000, it doesn't work with that so I set it to 911 as that signal is named T-05__Room_Menu_Show but that also doesn't work.

I also notice that Lights and Climate have an enable join, does this Rooms button need one also so it shows.

I also tried a new recent branch and have the same problem where I can't change rooms because that button is greyed out, is there something obvious that I am missing in the config that enables that Rooms button?

My available rooms is set to "" just like all the other panels but I am not understanding why the panels "Rooms" button might not work, any help with pointing me to the problem would be appreciated.

Sorry for might be a simple question but I've spent days trying to figure it out before I broke down and came here to ask for assistance.

Thanks

**Comment by adelyte-austin** [comment]
@DR7 Questions of all difficulty ranges are welcomed and appreciated! Don't hesitate to ask.

The TSR-302 in the demo is locked down to controlling the Media Room. It does not have a page for changing rooms, although one could easily be added. The Rooms button was added to indicate the possibility is there, but the remote is not currently configured to do so. 

As UIs are customized to projects, unused icons can be deleted or disabled. I would be happy to walk you through adding the room change to the remote. As you noticed, the programming is already be in place.

**Comment by DR7** [comment]
Hello Austin, thanks for the reply and I should mention the VT-Pro file does have a "Room" page and I have held this feedback high for the page from debugger and then I can control the other rooms but of course I can't leave that single held high all the time.

If you can tell me here how to enable it so it works I can do that or if you prefer I email you with the problem I can do that also, I am sure sooner or later someone else might wonder why the button is greyed out and then you might need to answer this again.

Thanks again Austin for all your help!
