### ISSUE TITLE
Add instructions for 2-Series conversion

### ISSUE THREAD

**Issue by adelyte-chris** [adelyte/crescendo#45]
Rather than maintain two separate programs, one for 2-Series and one for 3-Series, we should include instructions for converting the 3-Series program to 2-Series in the `documentation` folder.

**Comment by DR7** [comment]
I was going to ask about the 2 series code as I have a customer with an older system that used an iPad and MTX-3 that I was hoping to convert the system to Crescendo.

 If the instructions are clear I'm sure it wouldn't be too hard for most to convert, the part that might require lots of work is if one has to convert the current iPad template to work with 2 series and no SG objects, an example 2 series template even without the code with make the job much easier if one exists.

**Comment by adelyte-austin** [comment]
@DR7 See the updated readme on the home page for instructions on converting the program to 2-Series. Core3UI / Smart Graphics is actually supported on 2-Series processors, so you will be able to use Crestron App and the included iPad UI.

Legacy interfaces, like the MTX-3, do require some custom attention. Start by adding the panel and copying signals from the TSR-302 to your MTX-3. Comment out the Room-Sources Controller module for this interface, and use the `SIO` to create simple Routes~ like these:

Select Source 06: `\x50\x06`
Change to Room 03: `\x10\x03`

Your existing graphics file can be rejoined using Crescendo join standards.

**Comment by DR7** [comment]
Thanks again Austin, found the info and I will start working on it this weekend and again I really appreciate all of Adelyte's help with the framework.

**Comment by adelyte-austin** [comment]
If you are starting from the Loft demo, I would recommend getting the latest v2.1.3 before doing your conversion. If you already have custom edits to the **smw**, and convert from that point, there will be a little extra signal cleanup than the readme covers. The main purpose of v2.1.3 was to ease the conversion to 2-Series.

It's our pleasure to provide this resource to the community. Any further questions or feedback is welcomed!

**Comment by adelyte-austin** [comment]
I am attaching an archive of the loft demo that has been converted to a PRO2 for everyone's convenience.

A screen cast of the conversion process can be viewed here:
https://vimeo.com/193414047


[Crescendo Loft_PRO2_archive.zip](https://github.com/adelyte/crescendo/files/617305/Crescendo.Loft_PRO2_archive.zip)

**Comment by adelyte-austin** [comment]
[https://vimeo.com/193414047](url)

**Comment by adelyte-austin** [comment]
Finally, here is the Crestron answer ID for Smart Graphics tech tips and known issues. It states that all smart objects are compatible with 2-Series, but smart object "applications," like the media player, are not compatible.

https://support.crestron.com/app/answers/detail/a_id/5188

Marking this issue as closed.
