### ISSUE TITLE
Touchscreen Common Control Joins

### ISSUE THREAD

**Issue by ironcross13** [adelyte/crescendo#5]
The touchscreen module needs to have its common controls moved up by 100 (from start point 401 to start point 301) on the Generic Control Crosspoint Routing module  (S2.3.2).  As is there is currently no connection through to the source.

**Comment by adelyte-austin** [comment]
Good catch. This issue will be resolved this week and pushed to the development branch.

**Comment by adelyte-austin** [comment]
This is pushed to Develop. There is a high likelihood other joins inside Touchscreen are still out of place. I need a way to flag modules with an under-construction icon to show in the .smw :)

**Comment by adelyte-chris** [comment]
This issue was resolved sometime in the last several months.
