### ISSUE TITLE
Issue Loading Graphics

### ISSUE THREAD

**Issue by SeanPort** [adelyte/crescendo#53]
I'm having an issue loading graphics on my iPad with the file loaded to a CP3 processor. I have verified settings, project name, files in the file system, and an IP table connection. I have also recompiled and reloaded programming. Processor firmware is the latest as is the software on my PC and the iPad app is up to date. The iPad screen is stuck on loading interface.

**Comment by adelyte-austin** [comment]
@SeanPort have you checked that your web port matches?

**Comment by SeanPort** [comment]
Yes, the web port matches.


________________________________

**Comment by adelyte-austin** [comment]
If you load the iPad directly to your device does it work?

**Comment by SeanPort** [comment]
I will try that.


________________________________

**Comment by SeanPort** [comment]
It does not work when loaded locally. I'll screenshot my settings just for verification.


________________________________

**Comment by SeanPort** [comment]
I think these screenshots should give all pertinent info. I've added a colleague so he can see the settings as well. Nick, keep in mind this is my local processor so the IP info is different.


________________________________

**Comment by adelyte-austin** [comment]
Sean, I don't see any screen shots attached. Let's address this issue by email, as I don't suspect it is an issue with the code or graphics file.
