### ISSUE TITLE
Commenting Out Sub-systems?

### ISSUE THREAD

**Issue by benchris** [adelyte/crescendo#54]
Hello Adelyte,

Is there a way in simple where we can tell the Panel to not show the security sub-system or any sub-system for that matter?  Thanks and keep up the great work!!

Ben

**Comment by adelyte-austin** [comment]
Thanks @benchris!

The **Signal Mapping** buffer in the **System** folder has global signals for Has Lights, Climate, Security, Cameras. These signals are connected to all panels. Send a `1` or `0` through this buffer for each sub-system to enable or disable the main icons on the home page.

You can also switch the digital joins (11-16) in VTpro from enable to visibility on the objects if you prefer them hidden and not grayed out. Deleting unused items and re-centering the objects that remain is also a good approach.

**Comment by benchris** [comment]
Got it!
