### ISSUE TITLE
Directv Favorite Preset press and hold Feature

### ISSUE THREAD

**Issue by benchris** [adelyte/crescendo#55]
Hey Adelyte,

Not so much an issue, but have you had any thoughts to creating a module for a DirecTv Press and hold for favorite channels?  Similar to how it works on the Sirius/XM presets?

Just curious :)

Ben

**Comment by adelyte-austin** [comment]
We considered using the TV Presets smart application, but at the time were not happy with the overall performance and setup process required to include it in the 2.0 release.
A custom module that supports adding and editing presets would be a great feature. It would need to support channel # configuration from the user, and ideally, dynamic graphics that can be pulled off of the processor (eliminating the need to include them in the vtp file).

We will consider putting this on the road map for 2.2. Thank you for the request.
