### ISSUE TITLE
DVR & DVR Music

### ISSUE THREAD

**Issue by SeanPort** [adelyte/crescendo#57]
- In the DVR module, I think the __S__Number~ serial signal needs to connect to the [Serial_110FB] input on the Source module to properly display the number pad text on the touch panel.

- The __S__Preset_Value analog value in the DVR Music module does not seem to propagate to the parent DVR module to trigger a preset

**Comment by adelyte-austin** [comment]
Thank you @SeanPort. You are correct that these 2 items are broken.

Analog outputs from *Source* module were removed for v2.0.0 due to stale analog issues when interfaces connected to a source. I will look into adding a pathway between parent and child sources so the preset logic can be restored.

**Comment by SeanPort** [comment]
Thank you


________________________________
