### ISSUE TITLE
iPhone Page Drives

### ISSUE THREAD

**Issue by benchris** [adelyte/crescendo#58]
Hello Adelyte,

On the iPhone VtPro project I am having issues with page flips for a couple of listen sources.  Sonos is my first source in the list and when I press it, it changes to the Sonos page.  But when I press XM or FM, which are the next 2 selections in the list, they do not make the page flip to the source page.  The 4th one does make the page flip.

Any idea on why it is not making the page flip?  The pages work fine of the iPad and our TSW-1052.

Thanks,
Ben

**Comment by adelyte-austin** [comment]
Have you confirmed that the pages being driven by the program actually exist in the iPhone UI? XM and FM radio pages are not included in the released master interfaces, so they would have to be created.

Pages in graphics files use a +900 join offset. If a source is assigned a page `24`, the digital show page join in VTpro should be `924`

**Comment by benchris** [comment]
Yep. Sorry, totally forgot about that.
