### ISSUE TITLE
Rooms power on together

### ISSUE THREAD

**Issue by bp529** [adelyte/crescendo#59]
Hello,

First I want to thank the incredible team at Adelyte for publishing this framework. This is an amazing code set and thank you for sharing it. 

I have a total of 8 rooms. When I select a source in R-03, it always powers on R-02 and vice versa. I thought it might be to forgetting to define a source somewhere that was causing the Crosspoints to get confused. Have you ever seen this issue before? 

Thanks in advance. 

Brian

**Comment by adelyte-austin** [comment]
@bp529 You're welcome, and thanks for posting the issue. There was a similar issue reported (and fixed) that caused rooms to _report on_, but the switchers associated with that room did not actually trigger. This also only affected rooms above ID 09, so it sounds like you've run into something different.

Do the switchers of the un-selected room actually activate in your code? If you would send an archive to austin@adelyte.com I can investigate it for you.

**Comment by bp529** [comment]
@adelyte-austin thank you for the reply. I took one last review of my code and it was OE. I was missing an escape '\' in my audio switcher definition for R-02. Everything is now working as expected.
