### ISSUE TITLE
GUI Multi-Mode Buttons

### ISSUE THREAD

**Issue by ironcross13** [adelyte/crescendo#6]
The Multi-Mode Buttons (Multi-Mode Button_1) on both the Icon SM & Icon Lg subpages have duplicate Icon States.

Mode-25 & Mode-45 --> 93-Kaleidescape
Mode-26 & Mode-46 --> 73-DirecTV
Mode-27 & Mode-47 --> 80-Tivo
Mode-28 & Mode-48 --> 63-TV

I have an Excel Spreadsheet listing all modes available if needed.

**Comment by adelyte-austin** [comment]
This was done to provide mode support Video or Audio only sources, often for 2 logical sources using the same physical component. For instance, Kaleidescape Movies (OSD control) is page 45 / icon 45. Kaleidescape Music (SATP control) would be page 25 / icon 25. Cable / Cable music as another example. The icon values in the development branch are now defined by the "Dynamic Icon List" smart object. There will be 1 mode for each Neo icon using this standard.

**Comment by adelyte-austin** [comment]
A spreadsheet listing the icons/values for the Dynamic Icon List object would be very useful. Currently the attached .jpg is the only reference point.
![iconslgmodelist](https://cloud.githubusercontent.com/assets/2684605/8214622/7b530bb4-14f8-11e5-97c4-228d1ced3103.jpg)

**Comment by ironcross13** [comment]
Spreadsheet sent to you

**Comment by adelyte-austin** [comment]
Thank you for this. We will feature it in online documentation for icons modes.

**Comment by adelyte-austin** [comment]
All use of dynamic icon multi-mode buttons are unique for each mode, adhere to the Crestron standard defined by Smart Graphics themes. In addition the states will be documented online in the Crescendo docs.
