### ISSUE TITLE
Switcher: Power and Mute feedback to not update module

### ISSUE THREAD

**Issue by adelyte-austin** [adelyte/crescendo#61]
`Power_Is_On` and `Mute_Is_On` terminate into an disabled buffer. True device feedback should update internal **Switcher** logic so that input and output states are in sync.

**Comment by bp529** [comment]
Austin - Is Switcher v2.2 a drop in replacement for the original Switcher?

**Comment by adelyte-austin** [comment]
Yes. The v2.2 Switcher in the development branch feature/2.2 will be backwards compatible with v2.0 - v2.1.6, aside from the addition of a `Pulse Time` parameter, which has been placed at the bottom of the module so input configuration is not disturbed when upgrading programs. The module will lose the v2.2 appendix, and replace all internal instances of the module.

**Comment by adelyte-austin** [comment]
@bp529 Thank you for the question. I will tag an additional release (v2.1.7) to update **Switcher** with device power and mute syncing. This wlil be the final v2.1 release for any users not interested in upgrading to v2.2.
/estimate 2d

**Comment by bp529** [comment]
@adelyte-austin Thank you for the clarification. I am looking forward to using true Mute feedback as toggles were getting out of sync.

**Comment by adelyte-austin** [comment]
If discrete mute commands are available on a device, it's usually a good idea to use them instead of the toggle command. (I should be able to release v2.1.7 by mid week.)

**Comment by bp529** [comment]
@adelyte-austin I just updated Switcher from your latest master commit from 4 days ago. Unfortunately SIMPL didn't populate the `Pulse Time` parameter. It does appear at the bottom of the module after `Sources for Input 64`. It does not reflect the Parameter name and will not accept any user entered parameters in Ticks or Seconds. 

Importing a new instance of Switcher properly populates with the default value of 1t and allows modified parameters.

**Comment by adelyte-austin** [comment]
Have you performed a **project-resync**?

**Comment by bp529** [comment]
@adelyte-austin thank you sir. Forgot to resync the project only reloaded symbols.

**Comment by adelyte-austin** [comment]
Great. Make sure you overwrite the Room, Swamp and DM modules in your working directory too.
The changes are minor, but I will list them here so there is no question.

- Room - Added Debounce to Audio_Zone_Powered/Video_Zone_Powered logic to accompany new logic in Switcher.umc
- Crestron SWAMP/DM - Resynched instances of Switcher.umc
