### ISSUE TITLE
UI: Replace multi-mode button with Dynamic Icon Object

### ISSUE THREAD

**Issue by adelyte-austin** [adelyte/crescendo#62]
A new object has been introduced in recent smart graphics updates called the `Dynamic Icon Object` that has native support for the current 104 items in Crestron's Icons Lg/Sm set, as well as improved momentary feedback. Replacing all instances of the multi-mode source icon button (max 99) will provide native support for future theme icon additions.

**Comment by adelyte-austin** [comment]
Unfortunately Icon *AM-FM** occupies mode 0. Icon **Blank** is mode 102 which will require code changes for rooms that are powered off.

**Comment by ironcross13** [comment]
Can the upper limit for the Icon Parameter in the Self module be upped to 150 to allow for future headroom (as Crestron expands their default icon list)?

**Comment by adelyte-austin** [comment]
Yes, in fact this already done in branch **feature/2.2**, but this branch is not recommended for testing just yet. There are still some fundamental navigation issues in development.
