### ISSUE TITLE
UI: Convert UIs to single page

### ISSUE THREAD

**Issue by adelyte-austin** [adelyte/crescendo#63]
Crestron best practices dictate touchpanel files use the minimum number of pages necessary, opting for subpages wherever possible. This update will be a breaking change to previous 2.0 interfaces, both in program and graphics. Touchpanels on v2.2 will benefit from increased navigation speed and features.

**Comment by bp529** [comment]
@adelyte-austin what is the upgrade path from v2.0/2.1 to v2.2? I see there are breaking changes, but how does that affect current systems? Can the just the Touchscreen module be replaced or does this affect Room Controllers, Room-Source Controllers, etc?

**Comment by adelyte-austin** [comment]
Thanks for the inquiry @bp529. Please excuse the delayed response.

There should not be any breaking changes outside of the interface logic.
My preferred method for overhauling panel logic is to comment out all interfaces except T-01, then manually copy in the logic and signals from the target version. Once all signals are properly connected, use `Paste Special` and `Duplicate Device Programming` or `Copy all signals` to rebuild you panels. This is usually quick and less error prone than fixing each panel by hand.

If you have heavily customized interface logic, you may consider sticking with v2.1.9, at least until an official release, and you should still proceed with caution. The iPhone graphics file has not been reworked for subpages yet.

v2.2 also adds helpful optional outputs to many of the core modules in a new group called `Status` at the bottom of the modules. A program resynch _should_ be all that's required, and all new IOs are marked as optional.
