### ISSUE TITLE
Share Source?

### ISSUE THREAD

**Issue by Sjacques1975** [adelyte/crescendo#64]
I have experienced a glitch with the sharing of available sources. The audio sources always work but the video will not.
Example: I have (cable2) that is available in 3 rooms(Living,Master,Playroom) and when you select a room(Living) then select source (cable1) then if you change to source (cable2) then select share it will show only 1 room. If you then select say an audio room(Kitchen) then go back to the previous room(Living) and press share again then the other available rooms will appear.

If you watch very closely the share page will say (master) then quickly change to (playroom)

I can go in to debugger and see  Share Visible is low for that room and force it high and everything work.
Thanks

**Comment by adelyte-austin** [comment]
I'm don't recall seeing this issue in my production systems. Would you share a program archive so I can debug the issue @Sjacques1975? Send to austin@adelyte.com

**Comment by Sjacques1975** [comment]
[Crescendo Home_archive.zip](https://github.com/adelyte/crescendo/files/851307/Crescendo.Home_archive.zip)

I also will have the share button disappear randomly but same thing i can select another room and go back it will reappear.

**Comment by adelyte-austin** [comment]
The sharing menu controls as expected when I convert your program from an AV2 to AV3. 
> Cable 1 available to Living Room and Master Bed
> Cable 2 available to Living Room, Master Bed, and Playroom Right

It seems like the the 7 instances of the Rooms_Sources_Controller simpl+ module are fail on a 2-series when a source changes. (Tested on a PRO2 firmware version 4.008.0026)
@adelyte-chris

**Comment by Sjacques1975** [comment]
Can it be fixed? I am thinking of updating to a 3 series anyway.

**Comment by adelyte-austin** [comment]
Even the lowest 3-Series entry point (RMC3) as the main processor will improve menu speed across the board. At this time we do not have plans to optimize the Rooms Sources Controller for 2-Series processors. Any update to this will be posted here.
