### ISSUE TITLE
Current room populates in Sharing menu when ID > 09h

### ISSUE THREAD

**Issue by adelyte-austin** [adelyte/crescendo#67]
Reference #36 and #38 for historical cases of handling IDs higher than 09h.

**Comment by adelyte-austin** [comment]
![issue67](https://cloud.githubusercontent.com/assets/2684605/25461263/f25c789c-2ab5-11e7-87e9-fcbf6907a527.PNG)

**Comment by adelyte-chris** [comment]
What is the desired behavior?

**Comment by adelyte-austin** [comment]
The current room should not be visible in the **Sharing Menu**

**Comment by adelyte-chris** [comment]
All comparisons have to be done on the ID or index on both sides of the comparison. The offending code is an incompatibility between lines [756](https://github.com/adelyte/crescendo/blob/master/program/Rooms-Sources%20Controller.usp#L756) and [813](https://github.com/adelyte/crescendo/blob/master/program/Rooms-Sources%20Controller.usp#L813).

I would suggest changing it as follows:
```c
FUNCTION UpdateShareVisible(INTEGER room)
{
    /* ... */
    IF(room = IdToIndex(Room_Is))
    {
        Share_Visible[share] = 0;
    }
    /* ... */
}
