### ISSUE TITLE
Pre-Made Source Modules Icon & Page parameters

### ISSUE THREAD

**Issue by ironcross13** [adelyte/crescendo#7]
Is it really a good idea to have the icon and page parameters "inaccessible"/hard-coded on these (DirecTV, Cable, Blu-Ray, etc.)?  

Case in point is the Cable module could be used for a Dish Network source since both have the same page Up/Down functionality, but with the icon parameter not available to change it is necessary  to create a different module or add all the additional portions of the Cable module into the program alongside the source module.  Another example will likely be the use of the Blu-Ray module for Ultra HD Blu-Ray.

This also limits the ability to use a different icon if desired.

**Comment by adelyte-austin** [comment]
Agreed, it would make some of the modules more flexible. Hard coding certain parameters adds quality control, and improves "paste special" abilities of modules. A generic "DVR" module that exposes all needed commands is worth considering. Using a drop-down parameter to specify "DirecTV, Cable, Tivo, Dish" could also drive buttons to hide/show, allowing graphics files to have 1 single DVR page. Same for Blu-ray / DVD / Ultra.

**Comment by adelyte-austin** [comment]
Unfortunately SIMPL does not allow nesting drop-down parameters (value lists) into other modules. If DirecTV was selected in the program, and assigned a value of 73 internally, there is no way to pass that to Self as the icon value. The key is finding the right balance between flexibility and extra configuration.

**Comment by adelyte-chris** [comment]
We now have a generic DVR module with an exposed icon parameter.
