### ISSUE TITLE
Cameras in Crescendo Iphone 

### ISSUE THREAD

**Issue by marcoshemann** [adelyte/crescendo#71]
Dears,
Have you plans to add a cameras in Cescendo iPhone  VTP? like in Crescendo iPad?
Regards,

**Comment by adelyte-austin** [comment]
Yes the camera controls can be easily added to the iPhone using the same module and signals that are found on the iPad. If you're interested in contributing to the project you can modify the Loft from the master branch and issue a pull request. Otherwise give me until the end of next week and I will add this feature to the iPhones and release v2.1.9.

**Comment by marcoshemann** [comment]
Done.

**Comment by marcoshemann** [comment]
Dears,

I am working in shades panels, to Ipad, and following this way:


Button Shade :
Press Dig Joint:917 -> T-01__Shade_Controls_Show  ALREDY EXIST.
Enable Dig. Joint : 17 ->T-00__System_Has_Shade  NEW.
 





SubPage: [Device]Shades  in [Main]Menus   ( with joint 917)  Using 1 SubPage for each Shade ou Curtain.






Questions: 
1 - You agree with this way? Can I continuing?
2 - I will some help to do ShadesController, may I send questions to you by this email address?
3 - I make the pull request in master?

Tks,



 <http://mhemann.com.br/>	
MARCOS CENTENO HEMANN
Engenheiro/ Diretor
marcos@mhemann.com.br <mailto:marcos@mhemann.com.br>
+55 51 3737 9774 <tel:+55%2051%203737-9774> | +55 51 98115 9282 <tel:+55%2051%2098115-9282>
Av. Princesa Isabel, 844, 201 | Porto Alegre | RS
 <https://www.facebook.com/marcoshemann/>  <https://twitter.com/marcoshemann> <https://www.linkedin.com/company-beta/1934058/> <https://www.instagram.com/mhemanntecnologia/>




Em 13 de set de 2017, à(s) 13:02, Austin Hatchett <notifications@github.com> escreveu:

Yes the camera controls can be easily added to the iPhone using the same module and signals that are found on the iPad. If you're interested in contributing to the project you can modify the Loft from the master branch and issue a pull request. Otherwise give me until the end of next week and I will add this feature to the iPhones and release v2.1.9.

**Comment by marcoshemann** [comment]
Hi Dears,
You would have a date for when you would have time to give a valued in our suggestions of code?


 <http://mhemann.com.br/>	
MARCOS CENTENO HEMANN
Engenheiro/ Diretor
marcos@mhemann.com.br <mailto:marcos@mhemann.com.br>
+55 51 3737 9774 <tel:+55%2051%203737-9774> | +55 51 98115 9282 <tel:+55%2051%2098115-9282>
Av. Princesa Isabel, 844, 201 | Porto Alegre | RS
 <https://www.facebook.com/marcoshemann/>  <https://twitter.com/marcoshemann> <https://www.linkedin.com/company-beta/1934058/> <https://www.instagram.com/mhemanntecnologia/>




Em 13 de set de 2017, à(s) 13:02, Austin Hatchett <notifications@github.com> escreveu:

Yes the camera controls can be easily added to the iPhone using the same module and signals that are found on the iPad. If you're interested in contributing to the project you can modify the Loft from the master branch and issue a pull request. Otherwise give me until the end of next week and I will add this feature to the iPhones and release v2.1.9.
