### ISSUE TITLE
How to handle audio and video discretely in same room

### ISSUE THREAD

**Issue by sbarnesvta** [adelyte/crescendo#73]
Is there a way to handle audio and video sources discretely in a single room? I am playing around with this on my house system. Incredible work you guys have done to put this together. 

I have a single room with a TV and separate speakers. I am looking for a way to route video separate audio, IE I want to watch video sources 1 on the TV, but listen to a distributed audio source. The only way I have come up with to do this is to create (2) rooms called Room 1 Audio and Room 1 Video. This would give me the ability to separate the rooms, or use the share feature to share the sources. 

Thanks in advance.

**Comment by adelyte-austin** [comment]
Thank you @sbarnesvta.

Examine the Master Bedroom in The Loft demo. This room is setup similarly to what you've described, with local video sources but distributed audio from the headend SWAMP24x8.
To watch Tivo but listen to music from overhead speakers, select the video source first, then the music. Selecting an audio source typically will not clear video routing. TVs can be configured to power off, or be unaffected by incoming audio source routes*.

*Crescendo calls a the transmission of a Type+ID a Route~ (Routing Source 02 looks like this: `\x50\x02`) Not to be confused with routing a video or audio input.

The one caveat is that source controls will be for the audio source at the final step. Should you want to change the channel you'd need to select Tivo, and possibly select Sonos again to restore audio and volume control to your overheads. Try this out and let me know if you have further questions.

**Comment by sbarnesvta** [comment]
Thank you for the quick reply Austin, I'll check it out.
