### ISSUE TITLE
Crestron BIPAD and AAE control

### ISSUE THREAD

**Issue by adelyte-austin** [adelyte/crescendo#75]
These modules use the same fundamental switcher and volume logic as the SWAMP modules included in The Loft demo, but have different argument definitions to drive the `Power` and `Muted` inputs on their respective devices.

[Crestron_BIPAD8_AAE.zip](https://github.com/adelyte/crescendo/files/1434869/Crestron_BIPAD8_AAE.zip)

**Comment by DR7** [comment]
Thank you very much for this!
