### ISSUE TITLE
HR-150 handheld control 2 rooms?

### ISSUE THREAD

**Issue by DR7** [adelyte/crescendo#76]
Hello, I was wondering if its possible to have a HR-150 control two rooms easily with the current crosspoints and how it's done?

I currently have a HR-150 controlling two sources in the Master Bedroom and would like it to also control the same two source in the Great room by maybe just assigning a button to enable the Great Room crosspoint so its controls the room and maybe press another button to switch back to the Master Bedroom, I was thinking of maybe just assigning the red and green buttons at the bottom to change the rooms if this is possible? 

I realize the room will always default to the ID set in the crosspoint but would like to give them the option to use one remote for two room if it's fairly simple to do?

Thanks again!

**Comment by adelyte-austin** [comment]
All Crescendo interfaces are able to room switch. However, the HR-150 does not have the hooks exposed to do this, but it's very simple. I am not in a position right now to push this change to the project, but if you'd like to enable it on your system, use this screen shot as a guide:
 
![hr-150_rooms](https://user-images.githubusercontent.com/2684605/32571791-af026702-c496-11e7-94fa-f5b2d03c9d08.PNG)

**Comment by DR7** [comment]
Thank you very much Austin, I can get this working tonight after work and appreciate your time.
