### ISSUE TITLE
[Crescendo 2.0] Watch/Listen Source lists missing slots

### ISSUE THREAD

**Issue by adelyte-chris** [adelyte/crescendo#8]
The `Watch Source` and `Listen Source` lists are missing slots for the following data:
1. Source In Use (digital)
2. Source Rooms (serial)

The lists should support 48 items.

**Comment by adelyte-austin** [comment]
Added additional digital and serial "join increments" to objects in graphics for access in program but UI is still in draft phase.

**Comment by adelyte-austin** [comment]
The required slots are all present now. This issue is closed.
