### ISSUE TITLE
Question on Device-Defaults / List-Focus

### ISSUE THREAD

**Issue by etechy** [adelyte/crescendo#86]
It would be nice if in the room module when the light, shade parameters are 00 (maybe FF or other) it would show the last selected keypad, because now shows nothing and an item on the list highlighted.

**Comment by adelyte-austin** [comment]
The solution is to make sure all rooms have a default lighting-keypad, shade-keypad, or climate defined. Use a `House Scenes` lights default for rooms without their own keypad, or an adjacent climate. Focus the list on  `ID 01` if nothing else makes sense.

**Comment by etechy** [comment]
Thanks Austin, I can see that is always a possibility, I am just giving a use to the keypads which is not particularly related to the place the user is.
Then I use a separate type, which works independent from the lights, it has a different button on the main menu and a different look of the keypads.
The lights button remain as you describe or room-bound, but in the other button the keypads are more global or rather function-bound.

In that case I find jumping to the same place unnecessary and prefer that 00 instead of show-nothing were show-last.

**Comment by adelyte-austin** [comment]
There is no plan for modifying the lighting menus and keypads at this time. Send me a private message to discuss further enhancements.
