### ISSUE TITLE
New TSR and HR remotes?

### ISSUE THREAD

**Issue by steezywee** [adelyte/crescendo#87]
Hey there, 

Are you guys working on supporting the new TSR and HR remotes?

Love your work keep it up!!!!

Thanks

**Comment by adelyte-austin** [comment]
Thank you @steezywee!

We may release a future version with these devices defined. However, the `HR-150` and `TSR-302` resources available in the current demo are compatible with the new remotes. Let me know if you have specific questions after attempting a conversion and I can help address them.
