### ISSUE TITLE
Improve SWAMP volume control

### ISSUE THREAD

**Issue by adelyte-austin** [adelyte/crescendo#93]
#### Symptom
Sluggish volume control or runaways in large systems.

> Error: LogicEngine.exe [App 1] # 2018-10-31 13:36:09  # Ramp S-4.1.1.1.2:S-7.2.1: TRIED TO ADD RAMP-DOWN and got NULL back for the Add.

#### Solution
- Replace `ANALOG RAMP` symbol with `ANALOG INCREMENT` for each SWAMP output volume control.
- Remove volume up+down `PULSE STRETCHER` symbols inside `Rooms-Sources Controller.umc` required by the volume `RAMP` symbol to properly respond to presses from the **Sharing Menu**.

**Comment by adelyte-chris** [comment]
To the best of my knowledge, analog ramps (ramp control blocks) preferred
when interacting with Cresnet devices and analog increments (discrete
analog values) are preferred when interacting with Ethernet devices.
However, there are lots of counterexamples in both cases.

I wish Crestron would publish a set of best practices for different device
definitions.

**Comment by adelyte-austin** [comment]
Do you have any objection to using the `analog increment` solution on a BIPAD8 given the efficiency of the framework as a whole?

I believe the pulse stretchers were the primary culprit of the erratic behavior I witnessed. We determined lengthening the volume digital outputs that originate from the `usp` was required to get the `RAMP` to actually begin ramping from a single user press. The `AINC` works without the stretch so I prefer this version for cresnet and ethernet devices alike. @adelyte-chris

**Comment by adelyte-chris** [comment]
I know that the *PAD* switchers work better with analog ramps. We’ve been
chastised by Crestron support for using increments with them. I thought
this used to be a selectable option.

**Comment by adelyte-austin** [comment]
Output volume control has always been hard coded afaik.

**Comment by adelyte-austin** [comment]
Most end users are happy with 5% increments in volume adjustments. The increment symbol handles this well. I have not seen performance issues out of Crestron where this change is deployed. My experience is that it limits the possibility of runaway volume.
