### ISSUE TITLE
Code not switching CRCP between CEN-TRACK tuner 1 and 2

### ISSUE THREAD

**Issue by davidreevely** [adelyte/crescendo#94]
Audio switching is working and the UIs change to the correct page... however the tuner still displays the CRCP info for tuner 1.

any ideas?

I've developed the project from 2.1.6.   should I be using another build?

thanks

**Comment by adelyte-austin** [comment]
@davidreevely Thanks for posting the issue.

The analog input `device_select` on the media player object router is driven by `T-01__Source_Analog_101_Is`. You are most likely sending `Z__Constant_1d` to both sources @ `Analog_101_Fb` on the source module. Send a constant value of `2d` to Tuner 2 and the router module will update as expected.

**Comment by adelyte-austin** [comment]
You can safely replace the modules from the latest release with your 2.1.6 versions. The only program sync issue you should encounter is the `pulse time` parameter added to the bottom of `Switcher.umc`. At a minimum you should replace `IndexOf.usp`. #70

**Comment by davidreevely** [comment]
Thanks for the replies and I'll be trying to finish the code up tomorrow.

Can you direct me to the most up to date modules?  I've added the modules
from the 2.2 branch however I think they are older than the master branch.
I might be misunderstanding which are the most up to date.

David

**Comment by davidreevely** [comment]
CRCP for the ATC-AMFM2 is switching now thanks...

**Comment by adelyte-austin** [comment]
Glad to hear it. I would advise you to stay on the `master` branch and avoid the `2.2` branch as it contains breaking changes to argument definitions.
