### ISSUE TITLE
custom buttons on video page?

### ISSUE THREAD

**Issue by davidreevely** [adelyte/crescendo#95]
My client has a motorized TV mount in his office... How can I add a few buttons that only appears when the panel selects his office?  does the code support this?

**Comment by adelyte-austin** [comment]
There is no built in support for this but it can be easily added.
Use an `Analog Equate` symbol to evaluate the current room. See image. Use this as the digital visibility join on your button(s). You might want to use a popup subpage (built in joins for subpage start @ `971`). In that case add a settings button in the header bar that is visible only when the room is office.

![image](https://user-images.githubusercontent.com/2684605/58334174-fb293580-7e0c-11e9-8993-0d7273a9a81d.png)
