### ISSUE TITLE
sound bar question

### ISSUE THREAD

**Issue by davidreevely** [adelyte/crescendo#96]
Sorry if this is covered somewhere...

One of my video zones is using a Bose soundbar that only has an hdmi arc and toslink from the display.  

My question is, how should I configure the switcher symbol to account for this?

**Comment by adelyte-austin** [comment]
If you are controlling volume at the sound bar you can simply direct the display's `switcher` volume signals at the Bose for control. Set the volume to `relative` on this switcher.

Send me an email if you need additional support getting this to work in your project.
austin@adelyte.com
